test('\n${1}', async t => {
  try {
    ${2}
  } catch (err) {
    t.iferror(err)
  }

  t.end()
})
